pipeline {
    agent any
    tools {
      terraform 'terraform'
    }

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/NamunaGIT/cornerstone_project_Devops/tree/main/ELK%20Stack_deploy_using%20dockercompose'
            }
        }
        stage('Terraform init') {
            steps {
                sh 'terraform init'
            }
        }
        stage('Terraform Apply') {
            steps {
                sh 'terraform apply --auto-approve'
            }
        }
    }
}
